#!name=哔哩哔哩
#!desc=哔哩哔哩功能整合
# ==UserScript==
# @ScriptName        BiliBili_AdBlock_DIY
# @Author            @ddgksf2013, @blackmatrix7, @app2smile, @yjqiang
# @ForHelp           若有屏蔽广告的需求，可公众号后台回复APP名称
# @TaiWanBilibili    https://apps.apple.com/tw/app/id1517062289
# @HKBilibili        https://apps.apple.com/hk/app/id1517062289
# @FanjuChuChai      https://space.bilibili.com/11783021/
# @WechatID          公众号墨鱼手记
# @TgChannel         https://t.me/ddgksf2021
# @Contribute        https://t.me/ddgksf2013_bot
# @Feedback          📮 ddgksf2013@163.com 📮
# @UpdateTime        2022-10-02
# @ConfigVersion     V0.0.81
# @Attention         如果广告仍然存在，请清除缓存或卸载应用重新安装
# @Attention         如需引用请注明出处，谢谢合作！
# @Function          去广告配置（自用，不定期更新）
# @Suitable          自行观看“# > ”注释内容
# @ScriptURL         https://github.com/ddgksf2013/Cuttlefish/raw/master/Rewrite/AdBlock/Bilibili.conf
# ==/UserScript==
//B站解锁普通视频高码率仅适用国区粉色APP，外区为自我安慰
[MITM]
hostname = %APPEND% *.hdslb.com,app.bilibili.com,api.live.bilibili.com,api.vc.bilibili.com, api.bilibili.com, manga.bilibili.com, grpc.biliapi.net,api.biliapi.net, -broadcast.chat.bilibili.com, -*cdn*.biliapi.net, -*tracker*.biliapi.net, upos-hz-mirrorakam.akamaized.net

[Rule]
#防止tun模式下切区脚本失效
IP-CIDR,203.107.1.1/24,REJECT,no-resolve

[URL Rewrite]
#UPOS服务器替换为腾讯Cos对象存储
^https?:\/\/upos-hz-mirrorakam\.akamaized\.net\/(.*) https://upos-sz-mirrorcos.bilivideo.com/$1 302
# ～ BiliBili_哔哩哔哩_屏蔽广告浮窗@ddgksf2013
^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - reject-dict
# ～ BiliBili_哔哩哔哩_屏蔽IP请求@ddgksf2013
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - reject
# ～ BiliBili_哔哩哔哩_屏蔽DefaultWord@ddgksf2013
^https?:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/Default - reject
# ～ BiliBili_哔哩哔哩_应用开屏去广告@bm7
^https://app.bilibili.com/x/v2/splash/show - reject-dict
# ～ BiliBili_哔哩哔哩_Defaultword@ddgksf2013
^https://app.bilibili.com/x/v2/search/defaultwords - reject-dict
# ～ BiliBili_哔哩哔哩_Material_Ad@ddgksf2013
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - reject-dict
# ～ BiliBili_哔哩哔哩_小卡片广告@ddgksf2013
^https://api.bilibili.com/pgc/season/player/cards - reject-dict
# ～ BiliBili_哔哩哔哩_去除动态中的话题@bm7
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr - reject-dict
# ～ BiliBili_哔哩哔哩_漫画去广告@ddgksf2013
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash) - reject-dict
[script]
# ～ 嗶哩嗶哩繁體CC字幕轉中文簡體（2022-04-02）@ddgksf2013
简体字幕 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/i.\.hdslb\.com\/bfs\/subtitle\/.+\.json$,script-path=https://gitlab.com/ddgksf2013/Cuttlefish/-/raw/master/Script/bilibili_cc.js
# ～ BiliBili_哔哩哔哩_观影页面去广告@ddgksf2013
观影页广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js

# ～ BiliBili_哔哩哔哩_应用开屏广告预加载@yjqiang
开屏预加载 = type=http-response,requires-body=1,max-size=0,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_去除统一设置的皮肤@ddgksf2013
禁统一皮肤 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_1080P高码率+4K画质(番剧和影视除外)@ddgksf2013
解锁高码率 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_热搜发现@ddgksf2013
热搜 = type=http-response,requires-body=1,max-size=0,pattern=^https://app.bilibili.com/x/v2/search/square,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_屏蔽首页右上活动@ddgksf2013
屏蔽首页右上角活动 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity,script-path=https://gitlab.com/ddgksf2013/Cuttlefish/-/raw/master/Script/bilibili_json.js
# ～ BiliBili_哔哩哔哩_推荐去广告@ddgksf2013
推荐去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_追番去广告@ddgksf2013
追番去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_直播去广告@bm7
直播去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_标签页处理@ddgksf2013
标签页处理 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_我的页面处理@ddgksf2013
我的页面处理 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bilibili_json.js
# ～ BiliBili_哔哩哔哩_Proto去广告@app2smile
Proto去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.(view\.v1\.View\/View|dynamic\.v2\.Dynamic\/DynAll)$,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-proto.js
#B站切区
#Bili Region = type=http-response,pattern=^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/(pgc\/view\/v\d\/app\/season|x\/offline\/version)\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js

#可选, 适用于搜索指定地区的番剧
#Bili Search = type=http-request,pattern=^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/x\/v\d\/search(\/type)?\?.+?%20(%E6%B8%AF|%E5%8F%B0|%E4%B8%AD)&,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js
