#!name=BoxJs
#!desc=http://boxjs.com 0.12.2版本

[General]
force-http-engine-hosts = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net

[Script]
Rewrite: BoxJs = type=http-request,pattern=^https?:\/\/(.+\.)?boxjs\.(com|net),script-path=https://raw.githubusercontent.com/chavyleung/scripts/c890c1d23dd8911d4b14ccc4584f90881233608e/box/chavy.boxjs.js, requires-body=true, timeout=120

[MITM]
hostname = %INSERT% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net
