#!name=Github Private
#!desc=允许引用Github私有仓库/gist中的订阅分流，重写，脚本等配置文件。
#1️⃣ 登陆Github > 点击头像下拉菜单 > 选择Settings > 左边菜单栏选择最后一个Developer settings > 选择Personal access tokens > Generate new token > Note里面填写token名字 > ☑️下面的勾选框选择第一项repo打钩（所有子项目自动勾选）> 点击Generate token按钮保存并返回。
#2️⃣ 在BoxJS里面填入用户名（打开Github，浏览器地址栏应该会显示https://github.com/这里是你的用户名/）和上面的token。
#在需要引用的私库资源链接末尾加上enhanced-github  (凡是放在私库里的都要加，例如脚本，模块等)
#!author=Peng-YM

[MITM]
hostname = %APPEND% raw.githubusercontent.com, gist.githubusercontent.com

[Script]
Github Private = type=http-request, requires-body=0, pattern=^https?:\/\/(raw|gist)\.githubusercontent\.com.+enhanced-github$, script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/github-private-repo.js
