#!name=网易云去广告
#!desc=网易云去广告
#!搬运自DivineEngine

[URL Rewrite]
^https?:\/\/p\.du\.163\.com\/ad\/ - REJECT-DICT
^https?:\/\/support\.you\.163\.com\/xhr\/boot\/getBootMedia\.json - REJECT-DICT
^https?:\/\/interface(\d)?.music.163.com\/eapi\/ad\/ - REJECT-DICT
^https?:\/\/appconf\.mail\.163\.com\/mmad\/ - REJECT-DICT

[MITM]
hostname = %APPEND% appconf.mail.163.com,interface*.music.163.com,support.you.163.com,p.du.163.com
