#!name=QX重写转化&规则集解析
#!desc=使用方法在qx重写链接末尾加上qx 在surge模块链接末尾加sg 在规则集链接末尾加r_parser.list 支持QX & Clash规则集解析
#!author=@小白脸 @chengkongyiban
#!此模块已于模块商店模块合并https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/Block/LoonGalleryforShadowrocket.module

[Script]

QX转换 = type=http-request,pattern=qx$|qx\?(hnadd|hndel|n|y|x|del|i)=,requires-body=1,max-size=0,script-path=https://github.com/chengkongyiban/stash/raw/main/js/QX_Rewrite_Parser.js

#仅需要将Mock转为reject
Surge转换 = type=http-request,pattern=sg$|sg\?(hnadd|hndel|n|y|x|del|i)=,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Surge_to_Shadowrocket.js

规则集转换 = type=http-request,pattern=r_parser.list$|r_parser.list\?.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/stash/main/js/rule_parser.js

[MITM]
hostname = %APPEND% github.com:443, raw.githubusercontent.com:443,gist.githubusercontent.com,gitlab.com
