#!name=腾讯视频
#!desc=去除腾讯视频广告
#搬运自bai1zi，需先重装app，关掉模块，打开app登录账号后关掉app，再启用模块。

[Rule]
AND,((PROTOCOL,HTTPS), (DOMAIN,iacc.qq.com)),REJECT-NO-DROP
DOMAIN-SUFFIX,tetrack.qq.com,REJECT
DOMAIN-SUFFIX,tpns.tencent.com,REJECT
DOMAIN-SUFFIX,api.poll.video.qq.com,REJECT
DOMAIN-SUFFIX,static-res.qq.com,REJECT
DOMAIN-SUFFIX,stat.tpns.tencent.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
#解决部分视频无法播放
URL-REGEX,^http:\/\/.+\/vlive\.qqvideo\.tc\.qq\.com\/.+\.mp4,DIRECT

# > 开屏
[URL Rewrite]
^http:\/\/pgdt\.gtimg\.cn - REJECT-DICT
^http:\/\/.+\.tc\.qq\.com\/.+mp4 - REJECT-DICT
^http:\/\/wa\.gtimg\.com\/adxcdn\/.+\.jpg - REJECT-DICT


[Script]
腾讯 = type=http-request,pattern=^(https:\/\/i\.video|http:\/\/iacc)\.qq\.com\/$,requires-body=0,max-size=0,script-path=Tx.js


[MITM]
hostname = %APPEND% i.video.qq.com,iacc.qq.com
