#!name=腾讯视频
#!desc=去除腾讯视频广告
#搬运自bai1zi需先卸载重装，只保留开屏部分其他全部注释掉，打开app登录账号后关掉，在恢复注释就行。

[Rule]
AND,((PROTOCOL,HTTPS), (DOMAIN,iacc.qq.com)),REJECT-NO-DROP

# > 开屏
[URL Rewrite]
^http:\/\/pgdt\.gtimg\.cn - REJECT-DICT
^http:\/\/(.+\.tc\.qq\.com\/.+mp4|pgdt\.gtimg\.cn) - REJECT-DICT


[Script]
腾讯 = type=http-request,pattern=^(https:\/\/i\.video|http:\/\/iacc)\.qq\.com\/$,requires-body=0,max-size=0,script-path=Tx.js


[MITM]
hostname = %APPEND% i.video.qq.com,iacc.qq.com
