# ～ BiliBili_哔哩哔哩_屏蔽广告浮窗@ddgksf2013
//^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - reject-dict
# ～ BiliBili_哔哩哔哩_屏蔽IP请求@ddgksf2013
;^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - reject
# ～ BiliBili_哔哩哔哩_屏蔽DefaultWord@ddgksf2013
^https?:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/Default - reject
# ～ BiliBili_哔哩哔哩_应用开屏去广告@bm7
^https://app.bilibili.com/x/v2/splash/show - reject-dict