#!name=微博Lite
#!desc=微博轻享版去广告
[MITM]
hostname = %APPEND% *.uve.weibo.com, *api.weibo.cn, *api.weibo.com, h5.sinaimg.cn, new.vip.weibo.cn, *.sc.weibo.com, captcha.weibo.com, wx*.sinaimg.cn, js.t.sinajs.cn, *.e.weibo.com

[URL Rewrite]
#广告联盟，去开屏广告
e.qq.com - reject
gdt.qq.com - reject
l.qq.com - reject
adsmind.gdtimg.com - reject
adsmind.ugdtimg.com - reject
livep.l.t002.ottcn.com - reject
pgdt.ugdtimg.com - reject
splashqqlive.gtimg.com - reject
wa.gtimg.com - reject
wxsnsdy.wxs.qq.com - reject
wxsnsdythumb.wxs.qq.com - reject
ulogs.umengcloud.com - reject
ulogs.umeng.com - reject
open.e.kuaishou.com - reject
api-access.pangolin-sdk-toutiao.com - reject
sdk.open.talk.getui.net - reject
sdk.open.talk.getui.com - reject
errlog.umeng.com - reject
tnc3-aliec2.snssdk.com - reject
sf3-fe-tos.pglstatp-toutiao.com - reject
qzs.gdtimg.com - reject

# ～ WeiboLite_微博国际版_sdkad@ddgksf2013
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkad\.php - reject

# ～ WeiboLite_微博国际版_屏蔽search_suggest@ddgksf2013 
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/page\/get_search_suggest - reject-dict

# ～ WeiboLite_微博国际版_屏蔽searching_info@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*user&a=get_searching_info - reject

# ～ WeiboLite_微博国际版_屏蔽search_topic@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=search_topic - reject

# ～ WeiboLite_微博国际版_屏蔽开屏广告@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*ads - reject

[Script]

# ～ WeiboLite_微博国际版_关注tab去广告@ddgksf2013 
关注tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses\/friends_timeline,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_推荐tab|热门tab去广告@ddgksf2013
热门tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses\/unread_hot_timeline,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_趋势tab@ddgksf2013 
趋势tab = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_趋势tab去广告@ddgksf2013 
趋势tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js
