#!name=微博Lite
#!desc=微博轻享版去广告
#搬运自@ddgksf2013
[MITM]
hostname = %APPEND% *.uve.weibo.com, *api.weibo.cn, *api.weibo.com, h5.sinaimg.cn, new.vip.weibo.cn, *.sc.weibo.com, captcha.weibo.com, wx*.sinaimg.cn, js.t.sinajs.cn, *.e.weibo.com

[Rule]
DOMAIN-SUFFIX,e.qq.com,reject-dict
DOMAIN-SUFFIX,gdt.qq.com,reject-dict
DOMAIN-SUFFIX,l.qq.com,reject-dict
DOMAIN,adsmind.gdtimg.com,reject-dict
DOMAIN,adsmind.ugdtimg.com,reject-dict
DOMAIN,livep.l.t002.ottcn.com,reject-dict
DOMAIN,pgdt.ugdtimg.com,reject-dict
DOMAIN,splashqqlive.gtimg.com,reject-dict
DOMAIN,wa.gtimg.com,reject-dict

DOMAIN-SUFFIX,umengcloud.com,reject-dict
DOMAIN-SUFFIX,umeng.com,reject-dict
DOMAIN,sdk.e.qq.com,reject-dict
DOMAIN,mi.gdt.qq.com,reject-dict
DOMAIN,open.e.kuaishou.com,reject-dict
DOMAIN,api-access.pangolin-sdk-toutiao.com,reject-dict
DOMAIN,sdk.open.talk.getui.net,reject-dict
DOMAIN,sdk.open.talk.getui.com,reject-dict
DOMAIN,errlog.umeng.com,reject-dict
DOMAIN,tnc3-aliec2.snssdk.com,reject-dict
DOMAIN,sf3-fe-tos.pglstatp-toutiao.com,reject-dict
DOMAIN,qzs.gdtimg.com,reject-dict

DOMAIN-SUFFIX,alitui.weibo.com,reject-dict
DOMAIN-SUFFIX,beacon.sina.com.cn,reject-dict
DOMAIN,adimg.uve.weibo.com,reject-dict
DOMAIN,adimg.vue.weibo.com,reject-dict
DOMAIN,u1.img.mobile.sina.cn,reject-dict
DOMAIN,sax.sina.com.cn,reject-dict
DOMAIN,saxs.sina.com.cn,reject-dict
DOMAIN,saxn.sina.com.cn,reject-dict

[URL Rewrite]

# ～ WeiboLite_微博国际版_屏蔽search_suggest@ddgksf2013 
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/page\/get_search_suggest - reject-dict

# ～ WeiboLite_微博国际版_屏蔽searching_info@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*user&a=get_searching_info - reject

# ～ WeiboLite_微博国际版_屏蔽search_topic@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=search_topic - reject

# ～ WeiboLite_微博国际版_屏蔽开屏广告@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*ads - reject

[Script]

# ～ WeiboLite_微博国际版_关注tab去广告@ddgksf2013 
关注tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses\/friends_timeline,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_推荐tab|热门tab去广告@ddgksf2013
热门tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses\/unread_hot_timeline,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_趋势tab@ddgksf2013 
趋势tab = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js

# ～ WeiboLite_微博国际版_趋势tab去广告@ddgksf2013 
趋势tab去广告 = type=http-response,requires-body=1,max-size=0,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends,script-path=https://github.com/ddgksf2013/Cuttlefish/raw/master/Script/weibo_json.js
