#!name=微博Lite
#!desc=微博轻享版去广告
#需重装微博轻享版
#搬运自@ddgksf2013

[Rule]
#广告联盟，去开屏广告
DOMAIN-SUFFIX,sdkapp.uve.weibo.com,reject-dict
DOMAIN,adstrategy.biz.weibo.com,reject-dict
DOMAIN-SUFFIX,e.qq.com,reject-dict
DOMAIN-SUFFIX,gdt.qq.com,reject-dict
DOMAIN-SUFFIX,l.qq.com,reject-dict
DOMAIN,adsmind.gdtimg.com,reject-dict
DOMAIN,adsmind.ugdtimg.com,reject-dict
DOMAIN,livep.l.t002.ottcn.com,reject-dict
DOMAIN,pgdt.ugdtimg.com,reject-dict
DOMAIN,splashqqlive.gtimg.com,reject-dict
DOMAIN,wa.gtimg.com,reject-dict

DOMAIN,ulogs.umengcloud.com,reject-dict
DOMAIN,ulogs.umeng.com,reject-dict
DOMAIN,sdk.e.qq.com,reject-dict
DOMAIN,mi.gdt.qq.com,reject-dict
DOMAIN,open.e.kuaishou.com,reject-dict
DOMAIN,api-access.pangolin-sdk-toutiao.com,reject-dict
DOMAIN,sdk.open.talk.getui.net,reject-dict
DOMAIN,sdk.open.talk.getui.com,reject-dict
DOMAIN,errlog.umeng.com,reject-dict
DOMAIN,tnc3-aliec2.snssdk.com,reject-dict
DOMAIN,sf3-fe-tos.pglstatp-toutiao.com,reject-dict
DOMAIN,qzs.gdtimg.com,reject-dict

DOMAIN-SUFFIX,alitui.weibo.com,reject-dict
DOMAIN-SUFFIX,beacon.sina.com.cn,reject-dict
DOMAIN,adimg.uve.weibo.com,reject-dict
DOMAIN,adimg.vue.weibo.com,reject-dict
DOMAIN,u1.img.mobile.sina.cn,reject-dict
DOMAIN,sax.sina.com.cn,reject-dict
DOMAIN,saxs.sina.com.cn,reject-dict
DOMAIN,saxn.sina.com.cn,reject-dict

[URL Rewrite]

# > 微博国际版_hot_search@ddgksf2013
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php\?a=hot_search_users url reject-dict
# > 微博国际版_热推荐@ddgksf2013
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad\/weibointl\? url reject-dict
# > 微博国际版_屏蔽search_suggest@ddgksf2013
# ^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/page\/get_search_suggest url reject-dict
# > 微博国际版_屏蔽searching_info@ddgksf2013
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*user&a=get_searching_info url reject-dict
# > 微博国际版_屏蔽search_topic@ddgksf2013 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=search_topic url reject-dict
[Script]

# > 微博国际版_屏蔽开屏广告@ddgksf2013 
weibo_json = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*get_coopen_ads,requires-body=1,max-size=0,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博&国际版_sdkad@ddgksf2013
weibo_json = type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua),requires-body=1,max-size=0,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_趋势顶部CARD去广告@ddgksf2013
weibo_json = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends,requires-body=1,max-size=0,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_用户中心@ddgksf2013
weibo_json = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=user_center,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/weibo_json.js

[MITM]

hostname = %APPEND% *.uve.weibo.com,*api.weibo.cn,*api.weibo.com,h5.sinaimg.cn,new.vip.weibo.cn,*.sc.weibo.com,captcha.weibo.com,wx*.sinaimg.cn,js.t.sinajs.cn,*.e.weibo.com
