#!name=YouTube（改）
#!desc=去视频片头广告并解决闪屏问题
#搬运自@小白脸 
[Rule]
URL-REGEX,^https?:\/\/.+?\.googlevideo\.com\/.+&oda,REJECT-TINYGIF
URL-REGEX,^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/player\/ad_break\?key,REJECT-TINYGIF



[Script]
/油管 = type=http-request,pattern=^https?:\/\/.+?\.googlevideo\.com\/.+ctier=L,requires-body=0,script-path=https://github.com/chengkongyiban/shadowrocket/blob/main/scripts/YouTube.js?raw=ture



[MITM]
hostname = %APPEND% r*.googlevideo.com,youtubei.googleapis.com
